### PR TITLE
become root to install libselinux-python

### PR DESCRIPTION
**Pull request by brad**
##### CHECK LIST
Thank you for taking the time to work on a PR.

To ensure your PR is dealt with swiftly please check the following:

- [x] You have searched the repository for any relevant issues or PRs.
- [x] Your submissions are formatted according to the [ansible-lint](https://github.com/willthames/ansible-lint) guidelines.
- [x] You have provided a summary describing the change, including rationale and design decisions
- [ ] You have added additional spec tests to cover new feature or modification as needed

##### SUMMARY

Root is needed to install libselinux-python, but not requested.

### CODE REVIEW

**Comment by brad** [comment]
OK, now the tests are passing :smile: Just needed to update some of the packages used for testing

**Comment by smbambling** [comment]
This looks good I'm on my last day of vacation as soon as I get back to a terminal I'll approve and merge this in. 

Thanks for the update glad to see someone getting use out of these roles. Most of the Ansible roles are really stale and seem to lack a lot of functionality.

**Comment by smbambling** [comment]
Thanks for the work on updating to the latest version of Molecule to support newer versions Ansible.

**Comment by brad** [comment]
My pleasure! Thanks for the merge

**Pull request merged**
